apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sparkel-norg
  namespace: tbd
  labels:
    team: tbd
spec:
  port: 8080
  startup:
    path: isready
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 9
  liveness:
    path: isalive
  readiness:
    path: isready
  preStopHook:
    http:
      path: /stop
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 320Mi
  replicas:
    min: 2
    max: 2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  vault:
    enabled: true
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-sparkel-norg-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: speed-api
          namespace: tbd
        - application: norg2
          namespace: org
