apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sparkel-norg
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 1
  readiness:
    path: isready
    initialDelay: 1
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvsparkelnorg
  env:
    - name: NORG2_BASE_URL
      value: https://app.adeo.no/norg2/ws/Arbeidsfordeling/v1
    - name: PERSONV3_URL
      value: https://wasapp.adeo.no/tpsws/ws/Person/v3
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    - name: KAFKA_RAPID_TOPIC
      value: helse-rapid-v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: sparkel-norg-v1
