name: Build

on:
  workflow_call:
    inputs:
      push_image:
        description: 'Om bygget image skal pushes eller ikke'
        type: boolean
        default: true
        required: false
    outputs:
      image:
        description: "Navn på imaget som ble bygget"
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    permissions:
      contents: read
      id-token: write
      packages: read
    name: Build
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v5

      - name: gradle installDist
        run: ./gradlew installDist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          tag: ${{ github.sha }}
          push_image: ${{ inputs.push_image }}
