name: Bygg og deploy main

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deployDev:
    name: Deploy to dev
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev.yml
          IMAGE: ${{ needs.build.outputs.image }}

#  Nytt repo, venter til vi ser at dev går OK
#  deployProd:
#    name: Deploy to prod
#    needs: [ build ]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v6
#      - uses: nais/deploy/actions/deploy@v2
#        env:
#          CLUSTER: prod-gcp
#          RESOURCE: deploy/prod.yml
#          IMAGE: ${{ needs.build.outputs.image }}
